// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFQuDB7PYer0Jvlhi8mHuuyUjIV0nOFAw',
    appId: '1:83234913505:web:525d6c72630fd8ba85cba0',
    messagingSenderId: '83234913505',
    projectId: 'flutterdemo-8c52d',
    authDomain: 'flutterdemo-8c52d.firebaseapp.com',
    storageBucket: 'flutterdemo-8c52d.appspot.com',
    measurementId: 'G-E494Q7940Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiHrWJ__LdLJWKqJKGiY7CQKybWZu0a1g',
    appId: '1:83234913505:android:4133e5b07bdd0e7c85cba0',
    messagingSenderId: '83234913505',
    projectId: 'flutterdemo-8c52d',
    storageBucket: 'flutterdemo-8c52d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC92rNOYBSuALCaZqfFuRxU4Gv-_cD7Yig',
    appId: '1:83234913505:ios:e1dc62d25dbdda1485cba0',
    messagingSenderId: '83234913505',
    projectId: 'flutterdemo-8c52d',
    storageBucket: 'flutterdemo-8c52d.appspot.com',
    iosBundleId: 'com.example.untitledchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC92rNOYBSuALCaZqfFuRxU4Gv-_cD7Yig',
    appId: '1:83234913505:ios:e1dc62d25dbdda1485cba0',
    messagingSenderId: '83234913505',
    projectId: 'flutterdemo-8c52d',
    storageBucket: 'flutterdemo-8c52d.appspot.com',
    iosBundleId: 'com.example.untitledchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFQuDB7PYer0Jvlhi8mHuuyUjIV0nOFAw',
    appId: '1:83234913505:web:1abe43d2caad082285cba0',
    messagingSenderId: '83234913505',
    projectId: 'flutterdemo-8c52d',
    authDomain: 'flutterdemo-8c52d.firebaseapp.com',
    storageBucket: 'flutterdemo-8c52d.appspot.com',
    measurementId: 'G-ZWQPJW8E49',
  );
}
